version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: task_manager_app
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: task_manager_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: task_manager_db
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8000:80"  # Map host port 8000 to container port 80 for Nginx
        volumes:
            - .:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx config
        depends_on:
            - app
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    db_data:
